name: Primeiro Pipeline Python

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'app.py'
      - 'test_*.py'
      - '.github/workflows/pipeline.yml'
  pull_request:
    branches: [main]
    paths:
      - 'app.py'
      - 'test_*.py'
      - '.github/workflows/pipeline.yml'

jobs:
  testesoma:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: python -m pip install --upgrade pip pytest

      - name: Executar teste de soma
        run: python -m pytest -q test_soma.py

  testesubtracao:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: python -m pip install --upgrade pip pytest

      - name: Executar teste de subtração
        run: python -m pytest -q test_sub.py

  testemultiplicacao:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: python -m pip install --upgrade pip pytest

      - name: Executar teste de multiplicação
        run: python -m pytest -q test_mult.py

  testedivisao:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: python -m pip install --upgrade pip pytest

      - name: Executar teste de divisão
        run: python -m pytest -q test_div.py

  deploy:
    needs: [testesoma, testesubtracao, testemultiplicacao, testedivisao]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploy realizado com sucesso!"
                