name: Primeiro Pipeline Python e qualidade

on:
  push:
    branches: [ main ]

jobs:
  testesoma:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.12', '3.11', '3.10']
    runs-on: ${{matrix.os}}
    
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
          cache: 'pip'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar testes
        run: python -m pytest -q

  testesubtracao:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar testes
        run: python -m pytest -q

  testemultiplicacao:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar testes
        run: python -m pytest -q

  testedivisao:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar testes
        run: python -m pytest -q

  deploy:
    needs: [testesoma, testesubtracao, testemultiplicacao, testedivisao]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploy realizado com sucesso!"
