name: Primeiro pipeline JavaScript

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  testesoma:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Executar teste de soma
        run: npx jest test_soma.js


  testesubtracao:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Executar teste de subtração
        run: npx jest test_sub.js


  testemultiplicacao:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Executar teste de multiplicação
        run: npx jest test_mult.js


  testedivisao:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Executar teste de divisão
        run: npx jest test_div.js


  deploy:
    needs:
      - testesoma
      - testesubtracao
      - testemultiplicacao
      - testedivisao

    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Deploy realizado com sucesso!"